import os, subprocess, uuid, random
from pathlib import Path
from typing import List, Tuple

from core.transcriber import WordTimestamp
from core.downloader import FFMPEG_PATH, VideoDownloader

ASPECT_PRESETS = {
    "Portrait 9:16 (Shorts/TikTok)": {"w": 1080, "h": 1920, "label": "9:16"},
    "Landscape 16:9 (YouTube/FB)": {"w": 1920, "h": 1080, "label": "16:9"},
    "Square 1:1 (Instagram)": {"w": 1080, "h": 1080, "label": "1:1"},
}

SUBTITLE_COLORS = {"Kuning":"&H00FFFF&","Merah":"&H0000FF&","Hijau":"&H00FF00&",
    "Cyan":"&HFFFF00&","Pink":"&HFF00FF&","Putih":"&HFFFFFF&"}

COLOR_FILTERS = {
    "none": "",
    "warm": "colorbalance=rs=.1:gs=.05:bs=-.1,eq=saturation=1.1",
    "cool": "colorbalance=rs=-.1:gs=.05:bs=.1,eq=saturation=1.1",
    "vibrant": "eq=saturation=1.4:contrast=1.1:brightness=0.05",
    "vintage": "colorchannelmixer=.3:.4:.3:0:.3:.4:.3:0:.3:.4:.3,eq=saturation=0.6",
    "neon": "eq=saturation=1.8:contrast=1.2:brightness=0.1",
}

class SubtitleGenerator:
    @staticmethod
    def generate_ass(word_ts: List[WordTimestamp], out: str, color: str="&H00FFFF&",
                     font: str="Montserrat", size: int=48) -> str:
        if not word_ts: return ""
        ass = f"""[Script Info]
; Generated by VideoClipse
ScriptType: v4.00+
Collisions: Normal

[v4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font},{size},{color},&HFFFFFF&,&H000000&,&H000000&,1,0,0,0,100,100,0,0,1,3,1,5,10,10,40,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        lines, cur = [], []
        for wt in word_ts:
            cur.append(wt)
            if len(cur) >= 8: lines.append(cur); cur = []
        if cur: lines.append(cur)

        for lw in lines:
            stt, ett = lw[0].start, lw[-1].end
            def _fmt(s):
                h=int(s//3600); m=int((s%3600)//60); se=int(s%60); cs=int((s-int(s))*100)
                return f"{h}:{m:02d}:{se:02d}.{cs:02d}"
            parts = []
            for wt in lw:
                w = wt.word.strip()
                if not w: continue
                cs_dur = max(1, int((wt.end-wt.start)*100))
                ws = w.replace("{","\\{").replace("}","\\}")
                parts.append(f"{{\\kf{cs_dur}}}{ws} ")
            txt = "".join(parts).strip()
            if txt: ass += f"Dialogue: 0,{_fmt(stt)},{_fmt(ett)},Default,,0,0,0,,{txt}\n"
        with open(out,"w",encoding="utf-8") as f: f.write(ass)
        return out

class VideoProcessor:
    @staticmethod
    def _crop_scale_filter(aspect_key: str) -> str:
        """Generate FFmpeg crop+scale filter based on aspect ratio preset."""
        preset = ASPECT_PRESETS.get(aspect_key, ASPECT_PRESETS["Portrait 9:16 (Shorts/TikTok)"])
        tw, th = preset["w"], preset["h"]
        label = preset["label"]

        if label == "9:16":
            # Portrait: crop center vertical strip, scale to target
            return f"crop=ih*9/16:ih:(iw-ih*9/16)/2:0,scale={tw}:{th}"
        elif label == "16:9":
            # Landscape: crop center horizontal strip, scale to target
            return f"crop=iw:iw*9/16:0:(ih-iw*9/16)/2,scale={tw}:{th}"
        elif label == "1:1":
            # Square: crop center square, scale to target
            return f"crop=min(iw,ih):min(iw,ih):(iw-min(iw,ih))/2:(ih-min(iw,ih))/2,scale={tw}:{th}"
        return f"scale={tw}:{th}"

    @staticmethod
    def process_clip(in_vid: str, out: str, sub_ass: str="", wm_path: str="",
                     stt: float=0, ett: float=0, fade_in: float=0.5, fade_out: float=0.8,
                     speed: float=1.0, mirror: bool=False, color_filter: str="none",
                     noise_reduce: bool=False, aspect: str="Portrait 9:16 (Shorts/TikTok)") -> Tuple[bool, str]:
        if not Path(in_vid).exists(): return False, "File tidak ditemukan"
        if ett <= stt:
            r = subprocess.run([FFMPEG_PATH,"-v","error","-show_entries","format=duration",
                "-of","default=noprint_wrappers=1:nokey=1",in_vid], capture_output=True, text=True)
            try: dur = float(r.stdout.strip())
            except: dur = 60
        else: dur = ett - stt
        if dur <= 0: dur = 10
        fade_in = min(fade_in, dur/2); fade_out = min(fade_out, dur/2)
        fout_start = dur - fade_out

        # Base filter: crop + scale sesuai orientasi
        flt = [VideoProcessor._crop_scale_filter(aspect)]

        # Anti-copyright: mirror horizontal
        if mirror:
            flt.append("hflip")

        # Anti-copyright: speed (1.05x - 1.1x)
        if speed != 1.0:
            flt.append(f"setpts={1/speed}*PTS")

        # Color filter
        cf = COLOR_FILTERS.get(color_filter, "")
        if cf:
            flt.append(cf)

        # Noise reduction
        if noise_reduce:
            flt.append("hqdn3d=2:2:3:3")

        # Fades
        if fade_in > 0:
            flt.append(f"fade=t=in:st=0:d={fade_in}")
        if fade_out > 0 and fout_start > 0:
            flt.append(f"fade=t=out:st={fout_start}:d={fade_out}")

        # Subtitle
        if sub_ass and Path(sub_ass).exists():
            flt.append(f"ass={sub_ass}")

        # Watermark
        if wm_path and Path(wm_path).exists():
            flt.append("overlay=W-w-20:H-h-20:format=auto")

        # Audio speed adjustment
        audio_filters = []
        if speed != 1.0:
            audio_filters.append(f"atempo={min(speed, 2.0)}")

        cmd = [FFMPEG_PATH,"-y","-ss",str(stt),"-i",in_vid,"-t",str(dur),
            "-filter_complex",",".join(flt),"-c:v","libx264","-preset","fast",
            "-crf","23"]
        if audio_filters:
            cmd += ["-af",",".join(audio_filters)]
        cmd += ["-c:a","aac","-b:a","128k","-movflags","+faststart",out]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
            if r.returncode != 0: return False, r.stderr[-500:]
            return True, ""
        except subprocess.TimeoutExpired: return False, "Timeout"
        except Exception as e: return False, str(e)

    @staticmethod
    def auto_process(url: str, work_dir: str, min_dur: float = 30, max_dur: float = 60,
                     with_subtitle: bool = True, subtitle_color: str = "Kuning",
                     add_watermark: bool = False, watermark_path: str = "",
                     anti_copy: bool = True,
                     aspect: str = "Portrait 9:16 (Shorts/TikTok)") -> Tuple[bool, str, str, str, float, str, list]:
        os.makedirs(work_dir, exist_ok=True)
        audio, title, dur = VideoDownloader.download_audio(url, work_dir, max_dur=600)
        if not audio or not Path(audio).exists():
            return False, "", "Gagal download audio", "", 0, "", []

        from core.transcriber import AudioTranscriber
        text, wts = AudioTranscriber.transcribe(audio)
        if not text:
            text = f"Video: {title} ({dur:.0f}s)"

        from core.finder import ViralMomentFinder
        moments = ViralMomentFinder.find_moments(text, dur, wts)
        best = ViralMomentFinder.auto_best_moment(moments, min_dur, max_dur)

        clip = VideoDownloader.download_video_clip(url, work_dir, best.start_time, best.end_time)
        if not clip or not Path(clip).exists():
            return False, "", "Gagal download video", ""

        sub_path = ""
        if with_subtitle and wts:
            rel = [wt for wt in wts if wt.start < best.end_time and wt.end > best.start_time]
            if rel:
                shifted = [WordTimestamp(w.word, max(0,w.start-best.start_time), w.end-best.start_time) for w in rel]
                sub_path = os.path.join(work_dir, f"subs_{uuid.uuid4().hex[:8]}.ass")
                SubtitleGenerator.generate_ass(shifted, sub_path, SUBTITLE_COLORS.get(subtitle_color, "&H00FFFF&"))

        clip_dur = best.end_time - best.start_time
        out_path = os.path.join(work_dir, f"out_{uuid.uuid4().hex[:8]}.mp4")

        if anti_copy:
            speed = random.choice([1.0, 1.05, 1.07, 1.1])
            mirror = random.choice([True, False])
            color = random.choice(["none", "warm", "cool", "vibrant"])
            noise = random.choice([True, False])
        else:
            speed, mirror, color, noise = 1.0, False, "none", False

        ok, err = VideoProcessor.process_clip(clip, out_path, sub_path, watermark_path,
            0, clip_dur, 0.5, 0.8, speed, mirror, color, noise, aspect=aspect)
        if not ok:
            return False, "", f"Gagal render: {err}", "", 0, "", []

        return True, out_path, title, best.reason, clip_dur, text, moments

    @staticmethod
    def auto_process_multi(url: str, work_dir: str, n_clips: int = 5,
                           min_dur: float = 30, max_dur: float = 60,
                           with_subtitle: bool = True, subtitle_color: str = "Kuning",
                           watermark_path: str = "",
                           anti_copy: bool = True,
                           aspect: str = "Portrait 9:16 (Shorts/TikTok)") -> List[dict]:
        os.makedirs(work_dir, exist_ok=True)
        audio, title, dur = VideoDownloader.download_audio(url, work_dir, max_dur=600)
        if not audio or not Path(audio).exists():
            return []

        from core.transcriber import AudioTranscriber
        text, wts = AudioTranscriber.transcribe(audio)
        if not text:
            text = f"Video: {title} ({dur:.0f}s)"

        from core.finder import ViralMomentFinder
        moments = ViralMomentFinder.find_moments(text, dur, wts)
        top = ViralMomentFinder.top_moments(moments, text, dur, wts, n_clips, min_dur, max_dur)

        results = []
        for i, m in enumerate(top):
            clip = VideoDownloader.download_video_clip(url, work_dir, m.start_time, m.end_time)
            if not clip or not Path(clip).exists():
                continue

            sub_path = ""
            if with_subtitle and wts:
                rel = [wt for wt in wts if wt.start < m.end_time and wt.end > m.start_time]
                if rel:
                    shifted = [WordTimestamp(w.word, max(0,w.start-m.start_time), w.end-m.start_time) for w in rel]
                    sub_path = os.path.join(work_dir, f"subs_{uuid.uuid4().hex[:8]}.ass")
                    SubtitleGenerator.generate_ass(shifted, sub_path, SUBTITLE_COLORS.get(subtitle_color, "&H00FFFF&"))

            out_path = os.path.join(work_dir, f"clip_{i}_{uuid.uuid4().hex[:8]}.mp4")
            clip_dur = m.end_time - m.start_time

            # Unique anti-copy params per clip
            if anti_copy:
                speed = random.choice([1.0, 1.05, 1.07, 1.1])
                mirror = random.choice([True, False])
                color = random.choice(["none", "warm", "cool", "vibrant", "vintage"])
                noise = random.choice([True, False])
            else:
                speed, mirror, color, noise = 1.0, False, "none", False

            ok, err = VideoProcessor.process_clip(clip, out_path, sub_path, watermark_path,
                0, clip_dur, 0.5, 0.8, speed, mirror, color, noise, aspect=aspect)
            if ok:
                results.append({
                    "path": out_path, "title": title, "reason": m.reason,
                    "duration": clip_dur, "start": m.start_time, "end": m.end_time,
                    "transcript_snippet": m.transcript_snippet,
                    "speed": speed, "mirror": mirror, "color": color, "noise": noise
                })
        return results
